package hiber;
// Generated Dec 19, 2016 11:21:01 AM by Hibernate Tools 4.3.1



/**
 * Passenger generated by hbm2java
 */
public class Passenger  implements java.io.Serializable {


     private int psgId;
     private String username;
     private String password;
     private String firstname;
     private String lastname;
     private String address;
     private String telNo;
     private String email;

    public Passenger() {
    }

	
    public Passenger(int psgId) {
        this.psgId = psgId;
    }
    public Passenger(int psgId, String username, String password, String firstname, String lastname, String address, String telNo, String email) {
       this.psgId = psgId;
       this.username = username;
       this.password = password;
       this.firstname = firstname;
       this.lastname = lastname;
       this.address = address;
       this.telNo = telNo;
       this.email = email;
    }
   
    public int getPsgId() {
        return this.psgId;
    }
    
    public void setPsgId(int psgId) {
        this.psgId = psgId;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getTelNo() {
        return this.telNo;
    }
    
    public void setTelNo(String telNo) {
        this.telNo = telNo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


