package hiber;
// Generated Dec 19, 2016 11:21:01 AM by Hibernate Tools 4.3.1



/**
 * Payment generated by hbm2java
 */
public class Payment  implements java.io.Serializable {


     private String paymentId;
     private String ticketId;
     private String cardNumber;
     private String cardName;
     private String expMonth;
     private String expYear;

    public Payment() {
    }

	
    public Payment(String paymentId, String cardNumber, String cardName, String expMonth, String expYear) {
        this.paymentId = paymentId;
        this.cardNumber = cardNumber;
        this.cardName = cardName;
        this.expMonth = expMonth;
        this.expYear = expYear;
    }
    public Payment(String paymentId, String ticketId, String cardNumber, String cardName, String expMonth, String expYear) {
       this.paymentId = paymentId;
       this.ticketId = ticketId;
       this.cardNumber = cardNumber;
       this.cardName = cardName;
       this.expMonth = expMonth;
       this.expYear = expYear;
    }
   
    public String getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId;
    }
    public String getTicketId() {
        return this.ticketId;
    }
    
    public void setTicketId(String ticketId) {
        this.ticketId = ticketId;
    }
    public String getCardNumber() {
        return this.cardNumber;
    }
    
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }
    public String getCardName() {
        return this.cardName;
    }
    
    public void setCardName(String cardName) {
        this.cardName = cardName;
    }
    public String getExpMonth() {
        return this.expMonth;
    }
    
    public void setExpMonth(String expMonth) {
        this.expMonth = expMonth;
    }
    public String getExpYear() {
        return this.expYear;
    }
    
    public void setExpYear(String expYear) {
        this.expYear = expYear;
    }




}


