package hiber;
// Generated Dec 19, 2016 11:21:01 AM by Hibernate Tools 4.3.1



/**
 * Ticketinfo generated by hbm2java
 */
public class Ticketinfo  implements java.io.Serializable {


     private int ticketId;
     private int psgId;
     private int trainTravelId;
     private String departureDate;
     private String status;
     private int psgQuantity;
     private int priceAll;

    public Ticketinfo() {
    }

    public Ticketinfo(int ticketId, int psgId, int trainTravelId, String departureDate, String status, int psgQuantity, int priceAll) {
       this.ticketId = ticketId;
       this.psgId = psgId;
       this.trainTravelId = trainTravelId;
       this.departureDate = departureDate;
       this.status = status;
       this.psgQuantity = psgQuantity;
       this.priceAll = priceAll;
    }
   
    public int getTicketId() {
        return this.ticketId;
    }
    
    public void setTicketId(int ticketId) {
        this.ticketId = ticketId;
    }
    public int getPsgId() {
        return this.psgId;
    }
    
    public void setPsgId(int psgId) {
        this.psgId = psgId;
    }
    public int getTrainTravelId() {
        return this.trainTravelId;
    }
    
    public void setTrainTravelId(int trainTravelId) {
        this.trainTravelId = trainTravelId;
    }
    public String getDepartureDate() {
        return this.departureDate;
    }
    
    public void setDepartureDate(String departureDate) {
        this.departureDate = departureDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public int getPsgQuantity() {
        return this.psgQuantity;
    }
    
    public void setPsgQuantity(int psgQuantity) {
        this.psgQuantity = psgQuantity;
    }
    public int getPriceAll() {
        return this.priceAll;
    }
    
    public void setPriceAll(int priceAll) {
        this.priceAll = priceAll;
    }




}


