package hiber;
// Generated Dec 19, 2016 11:21:01 AM by Hibernate Tools 4.3.1



/**
 * TrainDetail generated by hbm2java
 */
public class TrainDetail  implements java.io.Serializable {


     private int trainTravelId;
     private String departureDate;
     private Integer price;
     private Integer availableSeat;

    public TrainDetail() {
    }

	
    public TrainDetail(int trainTravelId) {
        this.trainTravelId = trainTravelId;
    }
    public TrainDetail(int trainTravelId, String departureDate, Integer price, Integer availableSeat) {
       this.trainTravelId = trainTravelId;
       this.departureDate = departureDate;
       this.price = price;
       this.availableSeat = availableSeat;
    }
   
    public int getTrainTravelId() {
        return this.trainTravelId;
    }
    
    public void setTrainTravelId(int trainTravelId) {
        this.trainTravelId = trainTravelId;
    }
    public String getDepartureDate() {
        return this.departureDate;
    }
    
    public void setDepartureDate(String departureDate) {
        this.departureDate = departureDate;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Integer getAvailableSeat() {
        return this.availableSeat;
    }
    
    public void setAvailableSeat(Integer availableSeat) {
        this.availableSeat = availableSeat;
    }




}


